CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    role VARCHAR(255),
    created_at TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    city VARCHAR(255),
    state VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    favorite BOOLEAN,
    user_id BIGINT,
    created_at TIMESTAMP,
    CONSTRAINT fk_locations_users FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE risk_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature DOUBLE PRECISION,
    wind_speed DOUBLE PRECISION,
    rain_probability DOUBLE PRECISION,
    weather_condition VARCHAR(255),
    risk_level VARCHAR(255),
    recommendation VARCHAR(255),
    location_id BIGINT,
    created_at TIMESTAMP,
    CONSTRAINT fk_risk_reports_locations FOREIGN KEY (location_id) REFERENCES locations (id)
);

CREATE INDEX idx_locations_user_id ON locations (user_id);
CREATE INDEX idx_locations_user_favorite ON locations (user_id, favorite);
CREATE INDEX idx_risk_reports_location_id ON risk_reports (location_id);

INSERT INTO users (id, name, email, password, role, created_at) VALUES
    (1, 'Usuário Demonstração', 'user@orbitguard.com', '$2a$10$a.KjxwN7ciHQ1pTNClsaye75KSUqVWE4215nEFh9pj5O7.wcSbbb.', 'USER', CURRENT_TIMESTAMP),
    (2, 'Administrador OrbitGuard', 'admin@orbitguard.com', '$2a$10$z52El8m21GuInqBMZl5tv.THiQ9PWmIs3wXTkCAw2f0B5DSwnKKwC', 'ADMIN', CURRENT_TIMESTAMP);

INSERT INTO locations (id, name, city, state, latitude, longitude, favorite, user_id, created_at) VALUES
    (1, 'FIAP Paulista', 'São Paulo', 'SP', -23.561414, -46.655881, TRUE, 1, CURRENT_TIMESTAMP),
    (2, 'Porto de Santos', 'Santos', 'SP', -23.967882, -46.328887, FALSE, 1, CURRENT_TIMESTAMP),
    (3, 'Centro do Rio', 'Rio de Janeiro', 'RJ', -22.906847, -43.172897, TRUE, 1, CURRENT_TIMESTAMP),
    (4, 'Operação Curitiba', 'Curitiba', 'PR', -25.428954, -49.267137, FALSE, 2, CURRENT_TIMESTAMP);

INSERT INTO risk_reports (
    id,
    temperature,
    wind_speed,
    rain_probability,
    weather_condition,
    risk_level,
    recommendation,
    location_id,
    created_at
) VALUES
    (1, 27.4, 14.2, 22.0, 'Cloudy', 'LOW', 'Situação estável. Mantenha monitoramento.', 1, DATEADD('HOUR', -6, CURRENT_TIMESTAMP)),
    (2, 33.8, 24.6, 48.0, 'Rain', 'MEDIUM', 'Monitorar condições e evitar áreas de risco.', 1, DATEADD('HOUR', -3, CURRENT_TIMESTAMP)),
    (3, 29.1, 42.3, 78.0, 'Thunderstorm', 'HIGH', 'Evite deslocamentos e siga planos de contingência.', 2, DATEADD('HOUR', -2, CURRENT_TIMESTAMP)),
    (4, 18.7, 11.8, 15.0, 'Clear', 'LOW', 'Situação estável. Mantenha monitoramento.', 3, DATEADD('HOUR', -1, CURRENT_TIMESTAMP));

ALTER TABLE users ALTER COLUMN id RESTART WITH 3;
ALTER TABLE locations ALTER COLUMN id RESTART WITH 5;
ALTER TABLE risk_reports ALTER COLUMN id RESTART WITH 5;
